from .gemini_node import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .gemini_llm_node import NODE_CLASS_MAPPINGS as LLM_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LLM_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**IMAGE_MAPPINGS, **LLM_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**IMAGE_DISPLAY_MAPPINGS, **LLM_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']